export const USERS_ACTION_TYPES = {
  SET_USERS: "users/SET_USERS",
  UPDATE_USERS: "users/UPDATE_USERS",
  DELETE_USER: "users/DELETE_USER",
  GET_USERS: "users/GET_USERS",
  GET_SINGLE_USER: "user/GET_SINGLE_USER",
};
